version: '3'    
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #  env_file: ./postgres/postgres.env
    # build:
    #   context: ./postgres
    #   dockerfile: Dockerfile
    # ports:
    #   - "5432:5432"     
  nuxt:
    build:
        context: ./frontend
    command: bash -c "npm run start"
    volumes:
      - ./frontend:/frontend
    expose:
        - "3000"
    ports:
        - "3000:3000"
    depends_on:
        - django 
  django:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    # env_file: ./backend/django.env
    # links:
    #   - db
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
    expose:
      - '8000'